### ISSUE TITLE
Website www.sqliteodbc.org is down

### ISSUE THREAD

**Issue by matjon** [softace/sqliteodbc#2]
Hello,

The repository description (which is displayed on GitHub above folder view) reads currently:

> SQLite ODBC driver http://www.sqliteodbc.org

The website http://www.sqliteodbc.org does not work currently both in Firefox and Chrome.
Chrome reports a "DNS_PROBE_FINISHED_NXDOMAIN" error.

Thank You for developing this program.

**Comment by moorecode** [comment]
New location: http://www.ch-werner.de/sqliteodbc/

Looks like it was redirecting for a while, now the origin link is broken... https://web.archive.org/web/20180809083016/http://sqliteodbc.org/

**Comment by jarl-dk** [comment]
Re-established redirect.
